### ISSUE TITLE
Enhance Application Compatibility with PostgreSQL

### ISSUE THREAD

**Issue by jludwig** [janLo/wallabag-kindle-consumer#15]
### Summary

The application currently faces compatibility issues when configured to use a PostgreSQL database. This issue is to outline the specific problems encountered and propose a set of enhancements that will improve overall compatibility with PostgreSQL. These changes are expected to benefit not just PostgreSQL users but potentially enhance the robustness of database interactions for other databases as well.

### Problems Identified

1. **ENUM Type Naming**: The application fails because PostgreSQL requires ENUM types to be named. Several ENUM declarations are missing names, leading to a failure in creating the database schema.
2. **Configuration Handling**: The application does not find the `config.ini` file and does not clearly handle or report this situation, leading to a confusing startup experience.
3. **Database Permissions and Schema Existence**: The application assumes certain database permissions and schema existences without checks, which might not be the case for all users, leading to runtime errors.

### Proposed Enhancements

- Update all ENUM declarations in the models to include explicit names, ensuring compatibility with PostgreSQL's requirements.
- Improve the configuration loading mechanism to provide clear, informative error messages when `config.ini` is missing or corrupted, and improve the robustness of environment variable fallbacks.
- Implement initial checks for database connectivity, permissions, and schema existence, providing users with early and clear diagnostics if the setup is incorrect.

### Expected Benefits

- By addressing these issues, the application will become more compatible with PostgreSQL, offering users more flexibility in their choice of database systems.
- Improved error messages and configuration handling will make the application more user-friendly, reducing setup time and confusion.
- Early checks for database setup will prevent runtime errors, improving the overall user experience and reducing the need for troubleshooting.

### Additional Context

The need for these enhancements was identified during an attempt to set up the application with a PostgreSQL database, which resulted in multiple errors. Investigating these errors revealed that the application's current database handling is not fully compatible with PostgreSQL's strict requirements, particularly regarding ENUM naming and initial database setup. Implementing these changes will make the application more robust and easier to set up for new users.

**Comment by janLo** [comment]
Thank you! Merged.
